Add query multiple tables
KAYEMBAJONATHAN/Vet_Clinic pull request #3
Opened 2023-06-15 17:47 UTC by KAYEMBAJONATHAN

- Add Create a table named owners
- Add Create a table named species
- Add Modify animals table
- Add Modify your inserted animals 
- Abb Write queries using JOIN to answer different questions

2023-06-15 18:58 UTC, KAYEMBAJONATHAN commented
> * Add Create a table named owners
> * Add Create a table named species
> * Add Modify animals table
> * Add Modify your inserted animals
> * Abb Write queries using JOIN to answer different questions

![Screenshot 2023-06-15 203027 owenrs](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/94495beb-ae10-4e2e-a3fc-41f5820b74ab)
![Screenshot 2023-06-15 203154  species](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/5886e43f-94e1-4bd5-8611-14f86a4fa822)
![Screenshot 2023-06-15 203731 update](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/9021ff5d-1978-4232-b3ed-87db56397482)
![Screenshot 2023-06-15 203848 set](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/424fbe36-da32-4ef2-89ce-8950dd964a02)
![Screenshot 2023-06-15 204509 names](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/19605c43-1cbe-4933-ac2b-647c049f0944)
![Screenshot 2023-06-15 204720  a n w](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/61dc452c-e6d8-480e-b7e9-96c5a9a96e1d)
![Screenshot 2023-06-15 204944 f a](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/c1955563-ab5b-49a1-b1d2-917089f8fb8f)
![Screenshot 2023-06-15 205043 s m](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/d9a5938a-263e-442d-a59c-ee1ea8e0e1e9)
![Screenshot 2023-06-15 205206 d f](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/0592627f-1b2a-429c-9175-81c2f06721fe)
![Screenshot 2023-06-15 205329 ES](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/c37b4fc7-d7df-4da0-8dd4-895329672723)
![Screenshot 2023-06-15 205537 o f](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/bf416304-b36f-4c29-8186-b262c352deb9)

2023-06-15 19:59 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @KAYEMBAJONATHAN :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/93520178/9be65ef8-f95d-4de1-afab-2da664db226f)

## Highlights
- [x] Nice use of the JOIN command for the queries :+1: 

## Required Changes ♻️
_Check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 19:59 UTC, laiifuu commented on schema.sql
> +	REFERENCES owners(id)
When Making changes to a table, you should use the `ALTER TABLE` command. This way you wouldn't have to delete the table and re-create again. You did write altering commands in the `data.sql` file, so I suggest you revert this to how it was before.

2023-06-15 19:59 UTC, laiifuu commented on data.sql
> +ALTER TABLE animals ADD CONSTRAINT fk_owners FOREIGN KEY (owners_id) REFERENCES owners(id);
These commands modify the database's schema, I would suggest you place them in `schema.sql` file which is the appropriate file for them.

2023-06-15 19:59 UTC, laiifuu commented on data.sql
> +UPDATE animals SET species_id = 1 WHERE species_id ISNULL;
Kindly fix this typo: `ISNULL => IS NULL`

2023-06-15 19:59 UTC, laiifuu commented on queries.sql
> +SELECT animals.name, owners.full_name FROM animals JOIN owners ON animals.owners_id=owners.id WHERE full_name = 'Melody Pond';
This query should show the following animal names: `Charmander`, `Squirtle`, and `Blossom`. But according to your screenshot, the result is `Angemon` and `Boarmon` which belong to `Dean Winchester`. It's possible there was a mix up when setting the owner's id when updating the `animals` table. Kindly fix this issue.

2023-06-15 19:59 UTC, laiifuu commented on queries.sql
> +SELECT name AS digimon_animals, owners.full_name FROM (SELECT animals.name, animals.owners_id FROM animals JOIN SPECIES ON species_id = species.id WHERE species.name LIKE 'Digimon') AS all_digimons J
This query should show the following animal name: `Gabumon`. But according to your screenshot, the result is `Devimon` and `Plantmon` which belong to Bob. It's possible there was a mix up when setting the owner's id when updating the animals table. Kindly fix this issue.

2023-06-15 19:59 UTC, laiifuu commented on queries.sql
> +SELECT owners.full_name, COUNT(animals.name) AS all_animals from animals JOIN owners ON animals.owners_id = owners.id GROUP BY owners.full_name ORDER BY all_animals DESC LIMIT 1;
This query should show Melody Pond with 3 animals, but according to your screenshot, the result is Bob with 3 animals. It's possible there was a mix up when setting the owner's id when updating the animals table. Kindly fix this issue.

2023-06-16 07:59 UTC, KAYEMBAJONATHAN commented
See below the screen for what I have fixed

![Screenshot 2023-06-16 095635 fixed1](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/6d3552a4-c695-434c-b352-f0815335d09a)
![Screenshot 2023-06-16 095729 fixed 2](https://github.com/KAYEMBAJONATHAN/Vet_Clinic/assets/83698235/b5e8184b-3d0f-4aee-bbde-bb27684c8a2b)

2023-06-16 08:16 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @KAYEMBAJONATHAN, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 08:25 UTC, merged